spring:
  application:
    name: sentinel-vault-ai

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2
          temperature: 0.4
      embedding:
        options:
          model: mxbai-embed-large

  mongodb:
    uri: mongodb://localhost:27017/sentinel_vault_db

server:
  port: 8080
  servlet:
    context-path: /api